name: CloudCart CI

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test message
        run: echo "CloudCart CI Pipeline Started"