name: CloudCart CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Login to Azure Container Registry
        run: |
          az acr login --name cloudcartacr001


      - name: Build Backend Docker Image
        run: |
          docker build -t cloudcartacr001.azurecr.io/backend:${{ github.sha }} ./backend


      - name: Push Image to ACR
        run: |
          docker push cloudcartacr001.azurecr.io/backend:${{ github.sha }}