name: CloudCart CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Login to Azure using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # 3. Login to Azure Container Registry
      - name: Login to ACR
        run: |
          az acr login --name cloudcartacr001


      # 4. Build Backend Docker Image
      - name: Build Backend Docker Image
        run: |
          docker build \
          -t cloudcartacr001.azurecr.io/backend:${{ github.sha }} \
          ./backend


      # 5. Push Backend Image to ACR
      - name: Push Backend Image to ACR
        run: |
          docker push \
          cloudcartacr001.azurecr.io/backend:${{ github.sha }}


      # 6. Build Frontend Docker Image
      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t cloudcartacr001.azurecr.io/frontend:${{ github.sha }} \
          ./frontend


      # 7. Push Frontend Image to ACR
      - name: Push Frontend Image to ACR
        run: |
          docker push \
          cloudcartacr001.azurecr.io/frontend:${{ github.sha }}


      # 8. Connect GitHub Actions to AKS
      - name: Get AKS credentials
        uses: azure/aks-set-context@v4
        with:
          resource-group: rg-aks-lab
          cluster-name: cloudcart-aks


      # 9. Deploy Backend Image to AKS
      - name: Deploy Backend to AKS
        run: |
          kubectl set image deployment/cloudcart-backend \
          backend=cloudcartacr001.azurecr.io/backend:${{ github.sha }}


      # 10. Deploy Frontend Image to AKS
      - name: Deploy Frontend to AKS
        run: |
          kubectl set image deployment/cloudcart-frontend \
          frontend=cloudcartacr001.azurecr.io/frontend:${{ github.sha }}


      # 11. Verify Backend Rollout
      - name: Verify Backend Deployment
        run: |
          kubectl rollout status deployment/cloudcart-backend


      # 12. Verify Frontend Rollout
      - name: Verify Frontend Deployment
        run: |
          kubectl rollout status deployment/cloudcart-frontend